# Generated by Django 5.0.6 on 2024-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timescontrol',
            name='end_date',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timescontrol',
            name='start_date',
            field=models.TimeField(null=True),
        ),
    ]
