# Generated by Django 5.0.6 on 2024-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_alter_timescontrol_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
